### ISSUE TITLE
Parse csvs as structured data?

### ISSUE THREAD

**Issue by bmschmidt** [abbymullen/viraltexts-bookworm#1]
Rather than use regular expressions to parse the csvs which might throw errors and is hard to update, it will be faster and more reliable to read them using pandas which neatly associates all the data from the column headers.

``` python
import pandas as pd
import json
a = pd.read_csv("whatever you named David's csv")

metadata = open('jsoncatalog.txt','w')
texts = open('input.txt',"w")

for row in a.iterrows():
    # This is a dictionary of the row attributes with the csv's names
    indexed = row[1]; # Pandas stores the dict as the second item.
    metadata = dict()
    for key in ["date","cluster","ed","url","corpus"]: # This can be longer
        metadata[key] = indexed[key]
    metadata["filename"] = indexed["uid"]
    metadata.write(json.dumps(metadata) + "\n")
    texts.write("%d\t%s" %(indexed["uid"],indexed["text"].replace("\n"," ")))


```

**Comment by abbymullen** [comment]
I didn't know about pandas. Thanks.

When I do this, though, this is the error I'm getting:

File "text_breaking_VT.py", line 15, in <module>
    metadata.write(json.dumps(metadata) + "\n")
AttributeError: 'dict' object has no attribute 'write'
make: **\* [input.txt] Error 1

Since I'm not quite sure how all these things work together, I'm not having a lot of luck troubleshooting this.

**Comment by bmschmidt** [comment]
Oops, I named two different things `metadata`. I changed one of them to `metadata_file` below.

``` python
import pandas as pd
import json
a = pd.read_csv("whatever you named David's csv")

metadata_file = open('jsoncatalog.txt','w')
texts = open('input.txt',"w")

for row in a.iterrows():
    # This is a dictionary of the row attributes with the csv's names
    indexed = row[1]; # Pandas stores the dict as the second item.
    metadata = dict()
    for key in ["date","cluster","ed","url","corpus"]: # This can be longer
        metadata[key] = indexed[key]
    metadata["filename"] = str(indexed["uid"])
    metadata_file.write(json.dumps(metadata) + "\n")
    texts.write("%d\t%s\n" %(indexed["uid"],indexed["text"].replace("\n"," ")))
```

**Comment by bmschmidt** [comment]
And I forgot a newline in the texts field, I think.

**Comment by bmschmidt** [comment]
And one more change: the filename needs to be stored as a string, not an integer. Both these are now in the block above.

**Comment by abbymullen** [comment]
OK, all fixed. I think it should be working now. Thanks.
